POST localhost/api/users
Content-Type: application/json

{
  "firstName" : "Фарид",
  "lastName" : "Салихов",
  "birthday" : "1995-08-25",
  "email" : "farid@gmail.com",
  "hashPassword" : "qwerty003",
  "address" : "Казань, ул. Ибрагимова",
  "aboutMyself" : "Я студент"
}

###

GET localhost/users
Authorization: 25dd61f5-a613-4a60-9039-9426b704acd3

###

POST localhost/signIn
Content-Type: application/json

{
  "email" : "farid@gmail.com",
  "hashPassword" : "qwerty003"
}

###

PUT localhost/users/12
Content-Type: application/json
Authorization: 25dd61f5-a613-4a60-9039-9426b704acd3

{
  "address" : "Казань, ул. Короленко 45"
}

###

DELETE localhost/users/11
Authorization: 25dd61f5-a613-4a60-9039-9426b704acd3






