GET localhost/users

###

POST localhost/users
Content-Type: application/json

{
  "name" : "Вадим",
  "email" : "vadim@gmail.com",
  "hashPassword" : "Qwerty001"
}

###

POST localhost/events/2
Content-Type: application/json

{
  "date" : "2021-08-23",
  "startTime" : "14:30:00",
  "finishTime" : "14:40:00",
  "nameOfTheEvent" : "go to work"
}

###

GET localhost/user/2/events


###

POST localhost/events
Content-Type: application/json

{
"date" : "2021-09-30",
"startTime" : "11:15:00",
"finishTime" : "11:35:00",
"nameOfTheEvent" : "go to market",
"users" : [ {"id" : 2}]
}

###
POST localhost/signIn
Content-Type: application/json

{
  "email" : "vadim@gmail.com",
  "hashPassword" : "Qwerty001"
}

