GET localhost:8080/users

###

POST localhost:8080/users
Content-Type: application/json

{
  "name" : "Расим",
  "email" : "rasim@gmail.com"
}

###

POST localhost:8080/events/2
Content-Type: application/json

{
  "date" : "2021-08-23",
  "startTime" : "14:30:00",
  "finishTime" : "14:40:00",
  "nameOfTheEvent" : "go to work"
}

###

GET localhost:8080/user/2/events


###

POST localhost:8080/events
Content-Type: application/json

{
"date" : "2021-09-30",
"startTime" : "11:15:00",
"finishTime" : "11:35:00",
"nameOfTheEvent" : "go to market",
"users" : [ {"id" : 2}]
}


