GET localhost:8080/users

###

POST localhost:8080/users
Content-Type: application/json

{
  "name" : "Расим",
  "email" : "rasim@gmail.com"
}

###

POST localhost:8080/events/4
Content-Type: application/json

{
  "date" : "2021-08-23",
  "startTime" : "13:00:00",
  "finishTime" : "13:30:00",
  "nameOfTheEvent" : "to do homework"
}

###

GET localhost:8080/user/4/events
