<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Главная страница</title>
</head>
<body>
<h1>Добро пожаловать!!!</h1>
<div>
    <h4><a href="/signIn">Войти</a></h4>
    <h4><a href="/signUp">Зарегистрироваться</a></h4>
    <h4><a href="/admin">Страница администратора</a></h4>
</div>
</body>
</html>